config/routes.rb
 Rails.application.routes.draw do

  root 'welcome#index'
  get '/login', to: "sessions#new"
  post '/sessions', to: "sessions#create"
  delete '/logout', to: "sessions#destroy", as: 'logout'
  get '/potential_matches/:id', to: "potential_matches#redirect", as: "redirect_user"
  get '/matches/:id', to: "matches#redirect", as: "redirect_match"
  get '/users', to: "sessions#new"

  resources :users, except: :index
  resources :user_answers

  resources :matches


end

app/models/answer.rb
class Answer < ApplicationRecord
  has_many :user_answers
  has_many :users, through: :user_answers
  belongs_to :question 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
end

app/models/match_request.rb
class MatchRequest < ApplicationRecord
  belongs_to :user
end

app/models/potential_match.rb
class PotentialMatch < ApplicationRecord
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  validates :name, presence: true
  validates :mod, presence: true

  has_secure_password
  has_many :matches
  has_many :match_requests
  has_many :potential_matches
  has_many :user_answers
  has_many :answers, through: :user_answers

  def find_matches
    # counter = 0
    my_matches = []

    User.all.each do |user|
      i = 0
      counter = 0
      while i < user.answers.length
        if self.answers[i].id == user.answers[i].id && self.answers[i].category != "L"
          counter += 1
        elsif self.answers[i].category == "L" && user.answers[i].category == self.answers[i].category && self.answers[i].id != user.answers[i].id
          counter += 1
        end
        i += 1
      end

      # user.answers.each do |user_answer|
      #   self.answers.each do |self_answer|
      #     if self_answer.id == user_answer.id && self_answer.category != "L"
      #       counter += 1
      #     elsif self_answer.category == "L" && user_answer.category == self_answer.category && self_answer.id != user_answer.id
      #       byebug
      #       counter += 1
      #     end #end if
      #   end #next self_answer
      # end #next user_answer
      if counter >= 4 && !my_matches.include?(user) && user.id != self.id
        new_potential_match = PotentialMatch.create(user_id: self.id, user2_id: user.id)
        new_potential_match = PotentialMatch.create(user_id: user.id, user2_id: self.id)
        my_matches << user
      end #end if
    end #next user
    my_matches
  end #end method

  def show_categories
    comp = 0
    stress = 0
    leadership = 0
    category_string = ""

    self.answers.each do |answer|

      if answer.category == "C" && answer.id % 2 != 0
        comp += 1
      elsif answer.category == "S" && answer.id % 2 != 0
          stress += 1
        elsif answer.category == "L" && answer.id % 2 != 0
            leadership += 1
      end
    end

    if comp > 1
      category_string += "You find a competive atmosphere motivating! "
    elsif comp < 1
      category_string += "You enjoy working in a highly collaborative atmosphere. "
    else
      category_string += "You like working with dynamic individuals who help each other to be better. "
    end

    if leadership > 1
      category_string += "In groups you often take on a leadership role. "
    elsif leadership < 1
      category_string += "You work well in groups, supporting an idea to fruition. "
    else
      category_string += "In group projects you have a good balance of advocating for your own ideas and supporting others. "
    end

    if stress > 1
      category_string += "You thrive in high-intensity environments. "
    elsif stress < 1
      category_string += "You work best in a calm work environment. "
    else
      category_string += "You need some variety in your worklife to keep you interested. "
    end

    category_string
  end




end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :answer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    else
    end
  end

  def logged_in?
    !!current_user
  end

  def authorized
    redirect_to login_path unless logged_in?
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def redirect
    @match_request = MatchRequest.find(params[:id])
    @me = current_user
    @new_match = Match.new(user_id: @match_request.user2_id, user2_id: @match_request.user_id)
    @new_match2 = Match.new(user_id: @match_request.user_id, user2_id: @match_request.user2_id)

    if @new_match.valid?
      @new_match.save
      @new_match2.save

      @match_request2 = MatchRequest.where("user_id = ? and user2_id = ?", @match_request.user2_id, @match_request.user_id)

      @match_request.delete

      @match_request2.each do |obj|
        obj.delete
      end
    end

    @partner = User.find(@new_match.user2_id)
    redirect_to @me
  end

end

app/controllers/potential_matches_controller.rb
class PotentialMatchesController < ApplicationController
  def redirect
    @potential_match = PotentialMatch.find(params[:id])
    @user = User.find(@potential_match.user2_id)
    @me = current_user

    # @new_match_request = MatchRequest.new(user_id: @potential_match.user_id, user2_id: @potential_match.user2_id)
    @new_match_request2 = MatchRequest.new(user_id: @potential_match.user2_id, user2_id: @potential_match.user_id)

    if @new_match_request2.valid?
      # @new_match_request.save
      @new_match_request2.save

      @potential_match2 = PotentialMatch.where("user_id = ? and user2_id = ?", @potential_match.user2_id, @potential_match.user_id)

      @potential_match.delete

      @potential_match2.each do |obj|
        obj.delete
      end


    end
    redirect_to @me
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to user_path(user)
      else
        # @error = "Wrong username or password."
        redirect_to root_path
      end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/user_answers_controller.rb
class UserAnswersController < ApplicationController

  def new
    @user_answer = UserAnswer.new
  end

  def create
    UserAnswer.where(user_id: session[:user_id]).destroy_all
    @user_answer1 = UserAnswer.create(user_id: session[:user_id], answer_id: answer_params[:question_1])
    @user_answer2 = UserAnswer.create(user_id: session[:user_id], answer_id: answer_params[:question_2])
    @user_answer3 = UserAnswer.create(user_id: session[:user_id], answer_id: answer_params[:question_3])
    @user_answer4 = UserAnswer.create(user_id: session[:user_id], answer_id: answer_params[:question_4])
    @user_answer5 = UserAnswer.create(user_id: session[:user_id], answer_id: answer_params[:question_5])
    @user_answer6 = UserAnswer.create(user_id: session[:user_id], answer_id: answer_params[:question_6])
    PotentialMatch.where(user_id: session[:user_id]).destroy_all
    current_user.find_matches
    redirect_to user_path(current_user)
  end


  private
  def answer_params
    params.require(:user_answers).permit(:question_1, :question_2, :question_3, :question_4, :question_5, :question_6)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
    render :layout => "registration"
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    @questions = Question.all
  end

  def show
    @user = User.find(params[:id])
    @potential_matches = @user.potential_matches
    @requests = @user.match_requests
    @matches = @user.matches

  end

  private
  def user_params
    params.require(:user).permit(:name, :username, :mod, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "welcome"

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PickyPartners</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Merriweather:400,700|Muli:300,400,600" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <ul class="nav pt-3 ml-3 pb-2">
      <li class="nav-item">
      <% if logged_in? %>
      <p>Welcome, <%= current_user.name %>!</p>
      <% else %>
      <%= link_to "Login", root_path %>
      <% end %>
      </li>
      <li class="nav-item ml-4">
        <% if logged_in? %>
        <p><%= link_to "Take Quiz", new_user_answer_path %></p>
        <% end %>
      </li>
      <li class="nav-item ml-4">
        <% if logged_in? %>
        <p><%= link_to "My Profile", user_path(current_user) %></p>
        <% end %>
      </li>
      <li class="nav-item ml-4">
        <% if logged_in? %>
          <p><%= link_to "Logout", logout_path, method: 'delete' %></p>
        <% end %>
      </li>
    </ul>

  <%= yield %>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</body>
</html>

app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PickyPartners Welcome</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,700|Muli:300,400,600" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class="nav pt-3 ml-3 pb-2">
      <li class="nav-item">
      <% if logged_in? %>
      <p>Welcome, <%= current_user.name %>!</p>
      <% else %>
      <%= link_to "Login", login_path %>
      <% end %>
      </li>
      <li class="nav-item ml-4">
        <p><%= link_to "Take Quiz", new_user_answer_path %></p>
      </li>
      <li class="nav-item ml-4">
        <p><%= link_to "My Profile", user_path(current_user) %></p>
      </li>
      <li class="nav-item ml-4">
        <% if logged_in? %>
          <p><%= link_to "Logout", logout_path, method: 'delete' %></p>
        <% end %>
      </li>
    </ul>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/registration.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PickyPartners</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,700|Muli:300,400,600" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PickyPartners Welcome</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,700|Muli:300,400,600" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

app/views/user_answers/new.erb
<div class="container pt-3 pb-5">
  <h3>Find Your Perfect Match!</h3>
  <br>

  <%= form_tag '/user_answers', method: :post %>
  <% Question.all.each do |question| %>
      <h5 style="color:#A4CCC0;"><%= question.content %></h5>
      <% question.answers.each do |answer| %>
        <%= radio_button_tag "user_answers[question_#{question.id}]",  answer.id %>
        <%= label_tag answer.id, answer.content %><br>
      <% end %>
      <br>
  <% end %>
  <br>
  <%= submit_tag "Get My Partners!", class:"btn btn-primary btn-md" %>

</div>

app/views/users/edit.erb
<h2>Find Your Perfect Match</h2>

<%= form_for @user do |f|%>
  <% @questions.each do |question| %><br>
  <h3><%= question.ask %></h3>
    <%= f.radio_button "ask[#{question.id}]", ask.answer_1 %>
    <%= f.radio_button "ask[#{question.id}]", ask.answer_2 %>
  <% end %>
  <%= f.submit "Get Your Results!" %>
<% end %>

app/views/users/index.erb
<h1><% @users.each do |user| %></h1>
<%= user.name %>
<% end %>

app/views/users/new.erb
<div class="jumbotron registration-banner">
     <div class="container form-place">
       <h3 style="text-align:center;color: #fff; text-shadow: 1px 1px #000;">New Registration</h3>
        <br>


          <% if @user.errors.any? %>
            <div id="error_explanation" class="alert alert-danger">
              <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <%= form_for @user do |f|%>

          <div class="form-group mb-2 mr-sm-2">
            <% f.label :name %>
            <%= f.text_field :name, class:"form-control", placeholder:"Name" %>
          </div>

          <div class="form-group mb-2 mr-sm-2">
            <% f.label :username %>
            <%= f.text_field :username, class:"form-control", placeholder:"Username" %>
          </div>

          <div class="form-group mb-2 mr-sm-2">
            <%= f.select :mod, ['Mod 1','Mod 2','Mod 3','Mod 4','Mod 5'], {include_blank: "Select your mod!"}, { :class => 'custom-select' }  %>
          </div>

          <div class="form-group mb-2 mr-sm-2">
            <% f.label :password %>
            <%= f.password_field :password, class:"form-control", placeholder:"Password" %>
          </div>

          <div class="form-group mb-2 mr-sm-2">
            <% f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Confirm Password"%>
          </div>

          <div class="form-group mb-2 mr-sm-2">
            <%= f.submit "Sign Up!", class:"btn btn-primary", id:"new_user_button" %>
          </div>


          <% end %>

      </div>

</div>

app/views/users/show.erb
<% if @user.id == session[:user_id] %>
<div class="jumbotron profile-jumbotron profile-banner">


  <h3> <%= @user.name %>'s Work Personality</h3>
  <% if @user.answers.empty? %>
   <div class="about">
    You don't have any potential project partners! Take the quiz to find out who would work best with you!
  </div>
  <div class="btn btn-special">
    <%= link_to "Get Your Matches!", new_user_answer_path %>
    <br>
  </div>
    <% else %>
     <div class="about">
      <p><%= @user.show_categories %></p>
    </div>
      <h5>Want to try again?</h5>
      <div class="btn btn-special">
      <%= link_to "Find New Partners!", new_user_answer_path %>
      </div>

</div>

<div class="container bg-green">
  <div class="row mh-100">
    <div class="col">
      <h3> Potential Project Partners </h3>
            <h6>Send a request: </h6>
            <p>Your request will be sent automatically!</p>
              <% @potential_matches.each do |match| %>
                <% your_match = User.find(match.user2_id)%>

                <div class="btn btn-special">
                <%= link_to your_match.name, redirect_user_path(match.id), id: 'link-to-text-color'%> |
                <%= your_match.mod %><br>
              </div>

            <% end %>


    </div>
    <div class="col">
      <h3>Your Partner Requests</h3>
      <h6>Accept requests: </h6>
        <% @requests.each do |request| %>
        <% your_request = User.find(request.user2_id) %>
        <div class="btn btn-special">
        <%= link_to your_request.name, redirect_match_path(request.id)%> |
        <%= your_request.mod %> <br>
        <br/>
        <% end %>
    </div>
  </div>
</div>
<br>
  <div class="jumbotron">
      <h3 style="text-align:center;">Your Official Partners </h3>

    <br>
      <% @matches.each do |match| %>
      <% your_match = User.find(match.user2_id) %>
        <div class="btn-matches">
          <p><%= your_match.name %></p>
          <p style="opacity: .5;"><%= your_match.mod %></p>
          <br>
        </div>
      <% end %>

  <% end %>

  </div>
<% else %>
  <div class="container">
      <p> You are not authorized to visit this page. </p>
  </div>
<% end %>

app/views/welcome/index.erb
<div class="jumbotron banner">

  <h1 style="text-align:center; color: #fff; text-shadow: 1px 1px #000;"> Welcome to Picky Partners </h1>
  <p style="text-align:center; color: #fff; text-shadow: 1px 1px #000;"> Find Your Perfect Project Partner Today!</p>
  <br/>
    <div class="container custom-bg">

        <%= form_tag sessions_path do %>
        <div class="form-group">
           <%= label_tag "Username", "Username"%>
           <%= text_field_tag :username %>
         </div>

        <div class="form-group">
          <%= label_tag "Password" %>
          <%= password_field_tag :password %>
        </div>

        <p><%= submit_tag "Login", class:"btn btn-primary btn-md" %> || <%= link_to "Create An Account", new_user_path %></p>
        <% end %>


   </div>
</div>